# -*- coding: utf-8 -*-
"""MALL_CUSTOMERS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxr0s_DWqssB_bNKXmscELvjtRdRexBz
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')



from google.colab import files
files.upload()

df = pd.read_csv('Mall_Customers.csv')

df.head()

df.describe()

!pip install scipy

from scipy.cluster import hierarchy
plt.figure(figsize=(12,5))
z = hierarchy.linkage(df.iloc[:,3:5],method = 'ward')
dandogram = hierarchy.dendrogram(z,p=30)
plt.xlabel('coustomers')
plt.ylabel('distance')
plt.title('dandogram')

sns.set_style('whitegrid')
sns.displot(df['Age'],kde=True)
plt.xlabel('AGE')
plt.ylabel('Count')
plt.title('destribution of Age',fontsize=12)

sns.set_style('whitegrid')
sns.displot(df['Annual Income (k$)'],kde=True)
plt.xlabel('Annual Income (k$)')
plt.ylabel('Count')
plt.title('destribution of Annual Income ',fontsize=12)

sns.set_style('whitegrid')
sns.displot(df['Spending Score (1-100)'],kde=True)
plt.xlabel('Spending Score (1-100))')
plt.ylabel('Count')
plt.title('destribution of  Spending Score  ',fontsize=12)

from sklearn.cluster import KMeans
km = KMeans(n_clusters=5)
km_fit = km.fit(df.iloc[:,3:5])
label  =km.labels_

label1 = label.tolist()
dic = {0:'r',1:'b',2:'y',3:'c',4:'g'}
colors = ([dic.get(n, n) for n in label1])

plt.scatter(x=df.iloc[:,3].values,y=df.iloc[:,4].values,c=colors,label=dic)
plt.legend()

df['label']=label

sns.scatterplot(x = 'Annual Income (k$)',y = 'Spending Score (1-100)',hue="label",  
                 palette=['green','orange','brown','dodgerblue','red'], legend='full',data = df  ,s = 60 )

cust1 = df[df['label']==0]
cust2 = df[df['label']==1]
cust3 = df[df['label']==2]
cust4 = df[df['label']==3]
cust5 = df[df['label']==4]

print('number of customers in first group is :', len(cust1),'\n')
print('they are ', cust1['CustomerID'].values,'\n')
print('\n-----------------')


print('number of customers in second group is :', len(cust2),'\n')
print('they are ', cust2['CustomerID'].values,'\n')
print('\n-----------------')


print('number of customers in third group is :', len(cust3),'\n')
print('they are ', cust3['CustomerID'].values,'\n')
print('\n-----------------')

print('number of customers in fourh group is :', len(cust4),'\n')
print('they are ', cust3['CustomerID'].values,'\n')
print('\n-----------------')

print('number of customers in fifth group is :', len(cust5),'\n')
print('they are ', cust3['CustomerID'].values,'\n')
print('\n-----------------')

cust  = {'first':len(cust1),'second':len(cust2),'third':len(cust3),'fourth':len(cust4),'fifth':len(cust5)}

x = pd.Series(cust,name='cluster')
x

pd.DataFrame(data=x)

df.columns

df['Genre'][df['label']==1].value_counts()

df['Genre'][df['label']==4].value_counts()

sns.boxplot(x='Genre',y='Spending Score (1-100)',data=df)

